# config.toml

[dancers]
[[dancers.list]]
name = "Mr danceOmatic"
image = "/static/img/Martinus.png"
strength = 10
flexibility = 5

[[dancers.list]]
name = "Alex"
image = "/static/img/Jon.png"
strength = 8
flexibility = 7

[[dancers.list]]
name = "Meng-Ting"
image = "/static/img/Mengting.png"
strength = 5
flexibility = 10

[[dancers.list]]
name = "Meng-Yuan"
image = "/static/img/Mengyuin.png"
strength = 8
flexibility = 7

[songs]
available = [
    "song1.mp3",
    "song2.mp3",
    "song3.mp3"
]

# Add more configuration sections as needed